version: 2.1

orbs:
  composer: itinerisltd/composer@0.2

workflows:
  test:
    jobs:
      - composer/install:
          name: style-check
          executor: composer/seven
          post-steps:
            - composer/exec:
                command: style:check
      - composer/install:
          name: phpstan-analyse
          executor: composer/seven
          post-steps:
            - composer/exec:
                command: phpstan:analyse
      - composer/install:
          name: codeception-test
          executor: composer/seven
          post-steps:
            - composer/exec:
                command: test

